Lint/Eval:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# When define classes and modules, we use
#   nested style for those who are independent from BioTCM
#   compact style for  those who are not
Style/ClassAndModuleChildren:
  Enabled: false

# Example usage:
#
#   def print_msg(index = nil)
#     msg = messages[index] or return nil
#     ...
#   end
Style/AndOr:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true

# TOFIX

Metrics/MethodLength:
  Max: 72

Metrics/LineLength:
  Max: 405

Metrics/BlockNesting:
  Max: 4

Metrics/AbcSize:
  Max: 117

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 17
